version: "3.9"

services:
  app:
    container_name: flask_app
    restart: always
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - data:/opt/data

volumes:
  data:
